# Generated by Django 5.2.5 on 2025-08-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.URLField(max_length=500)),
                ('objective', models.TextField()),
                ('audience', models.TextField()),
            ],
            options={
                'db_table': 'tb_subjects',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='subjects.subject')),
            ],
            options={
                'db_table': 'tb_curriculums',
            },
        ),
    ]
