# Generated by Django 5.2.5 on 2025-08-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('frequency_type', models.CharField(max_length=50)),
                ('frequency_count', models.IntegerField()),
                ('class_count', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='subjects.subject')),
            ],
            options={
                'db_table': 'tb_applies',
            },
        ),
    ]
