# Generated by Django 5.2.5 on 2025-08-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_applies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applies',
            new_name='Apply',
        ),
    ]
