# Generated by Django 5.2.5 on 2025-08-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_rename_applies_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
