# Generated by Django 5.2.5 on 2025-08-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_rename_subject_id_apply_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
