# Generated by Django 5.2.5 on 2025-09-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
    ]
